name: Create Release

on:
  workflow_dispatch:

jobs:
  CreateRelease:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          ref: AssetStoreRelease

      - name: Merge master into AssetStoreRelease
        run: |
          git fetch origin master --depth 1
          git rebase origin/master

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.301

      - name: Run CreateRelease.cs
        run: |
          dotnet script .github/CreateRelease.cs

      - name: Commit and Push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add Assets/Mirror/version.txt
          git commit -m "release!: Asset Store Release" -a
          git push origin AssetStoreRelease
